version: "3.8"
services:
  db:
    image: postgres
    container_name: hbc_postgresDB
    restart: always
    networks:
      - bridge
    ports:
      - "5432:5432"
    env_file: 
      - postgres.env
    volumes:
      - pgdata:/var/lib/postgresql
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hbc_backend
    restart: always
    networks:
      - bridge
    ports:
      - "8080:8080"
      - "8081:8081"
networks:
  bridge:
volumes:
  pgdata: